extra_css:
  - assets/styles/extra.css

site_name: DiracX
repo_url: https://github.com/DIRACGrid/diracx
site_url: https://diracx.io/
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # primary: black
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.svg
  icon:
    logo: logo
  features:
    - navigation.instant
    - navigation.instant.progress
    - header.autohide
    - navigation.tabs

nav:
  - Home: index.md
  - Roadmap: roadmap.md
  - Users:
    - Introduction: user/index.md
    - Tutorials: user/tutorials/index.md
    - How-To: user/how-to/index.md
    - Explanations: user/explanations/index.md
    - Reference: user/reference/index.md
  - Administrators:
    - Introduction: admin/index.md
    - Tutorials: admin/tutorials/index.md
    - How-To: admin/how-to/index.md
    - Explanations: admin/explanations/index.md
    - Reference: admin/reference/index.md
  - Developers:
    - Introduction:dev/index.md
    - Tutorials: dev/tutorials/index.md
    - How-To: dev/how-to/index.md
    - Explanations: dev/explanations/index.md
    - Reference: dev/reference/index.md
  - Project:
    - Introduction: project/index.md
    - Consortium: project/consortium.md
